import type { NextPage } from 'next';
import Head from 'next/head';
import { PageWrapper, Page } from 'components';

const Category: NextPage = () => {
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page></Page>
        </PageWrapper>
    );
};

export default Category;
