import type { NextPage } from 'next';
import Head from 'next/head';
import {
    Hero,
    PageWrapper,
    Navigation,
    Sidebar,
    ScrolledNavigation,
    CategoryCard,
    PageSplitter,
    Card,
    ContentSplitter,
} from 'components';
// import { createClient } from 'next-sanity';

// const client = createClient({
//     projectId: '3zonnd0w',
//     dataset: 'production',
//     apiVersion: '2022-08-28',
//     useCdn: false,
// });

const Home: NextPage = () => {
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sidebar />
            <ScrolledNavigation />
            <Navigation />
            <Hero />
            <PageSplitter h2Content="Best Seller" pContent="Phasellus faucibus non libero" />
            <ContentSplitter>
                <CategoryCard />
                <CategoryCard />
                <CategoryCard />
            </ContentSplitter>
            <PageSplitter h2Content="Best Seller" pContent="Phasellus faucibus non libero" />
            <ContentSplitter>
                <Card className="" href="#" h2Content="Crew neck sweater" pContent="50" />
                <Card className="" href="#" h2Content="Crew neck sweater" pContent="50" />
                <Card className="" href="#" h2Content="Crew neck sweater" pContent="50" />
            </ContentSplitter>

            {/* <div className="h-[200vh]"></div> */}
        </PageWrapper>
    );
};

export default Home;

// export async function getStaticProps() {
//     const article = await client.fetch(`*[_type == "article"]`);
//     console.log(article, 'data');
//     return {
//         props: { article },
//     };
// }
