import type { NextPage } from 'next';
import Head from 'next/head';
import { Hero, PageWrapper, Navigation } from 'components';
// import { createClient } from 'next-sanity';

// const client = createClient({
//     projectId: '3zonnd0w',
//     dataset: 'production',
//     apiVersion: '2022-08-28',
//     useCdn: false,
// });

const Home: NextPage = () => {
    return (
        <PageWrapper className="justify-self-center w-full col-start-2 col-end-3 h-[200vh]">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <Hero />
        </PageWrapper>
    );
};

export default Home;

// export async function getStaticProps() {
//     const article = await client.fetch(`*[_type == "article"]`);
//     console.log(article, 'data');
//     return {
//         props: { article },
//     };
// }
